source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'mongo_mapper'
gem 'opentok', '~> 2.2.1'
gem 'hashids'
gem 'urbanairship'
gem 'aescrypt'
gem 'json-schema'
gem 'bcrypt-ruby', require: 'bcrypt'
gem 'rufus-scheduler'
gem "activesupport"
gem 'bson_ext'
gem 'mandrill-api'
gem 'tzinfo'
gem 'tzinfo-data'
gem 'language_list'

gem 'event_bus'
gem 'sinatra-jsonp'
gem 'zero_push'
group :development, :test do
  gem 'rspec-mocks'
  gem 'factory_girl'
  gem 'rspec'
  gem 'growl-rspec'
  gem 'shoulda'
  gem 'rest-client'
  gem "rack-test", require: "rack/test"
  gem 'guard'
  gem 'guard-rspec'
  gem 'rspec-autotest'
  gem 'timecop'

  #Pry
  gem 'pry'
  gem 'pry-rescue'
  gem 'pry-doc'
  gem 'awesome_print'
  gem 'pry-stack_explorer'
  gem 'pry-byebug'
end
gem 'rake'

gem 'newrelic_rpm'
gem 'redis'
gem 'logster'
